# Generated by Django 5.2.1 on 2025-05-11 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('drank_water', models.BooleanField(default=False)),
                ('workout_1', models.BooleanField(default=False)),
                ('workout_2', models.BooleanField(default=False)),
                ('read_pages', models.BooleanField(default=False)),
                ('is_day_completed', models.BooleanField(default=False)),
                ('no_junk_food', models.BooleanField(default=False)),
                ('no_alcohol', models.BooleanField(default=False)),
                ('progress_photo', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'unique_together': {('user', 'day')},
            },
        ),
    ]
