# Generated by Django 5.2.1 on 2025-05-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('drank_water', models.BooleanField(default=False)),
                ('workout_1', models.BooleanField(default=False)),
                ('workout_2', models.BooleanField(default=False)),
                ('read_pages', models.BooleanField(default=False)),
                ('no_junk_food', models.BooleanField(default=False)),
                ('no_alcohol', models.BooleanField(default=False)),
                ('progress_photo', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
